=== folio-org/mgr-tenant-entitlements/src/main/resources/swagger.api/schemas/applicationFlow.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "applicationEntitlement.json",
  "title": "Application Entitlement Flow Schema",
  "description": "An entitlement flow result for a single application",
  "type": "object",
  "properties": {
    "id": {
      "description": "An application entitlement flow identifier",
      "type": "string",
      "format": "uuid"
    },
    "applicationId": {
      "description": "An application descriptor identifier",
      "type": "string"
    },
    "tenantId": {
      "description": "A tenant identifier",
      "type": "string",
      "format": "uuid"
    },
    "flowId": {
      "description": "An entitlement flow identifier",
      "type": "string",
      "format": "uuid"
    },
    "type": {
      "description": "Application flow entitlement type",
      "$ref": "types/entitlementType.json"
    },
    "status": {
      "description": "Application flow execution status",
      "$ref": "types/executionStatus.json"
    },
    "startedAt": {
      "description": "An application flow start timestamp",
      "type": "string",
      "format": "date-time"
    },
    "finishedAt": {
      "description": "An application flow end timestamp",
      "type": "string",
      "format": "date-time"
    },
    "stages": {
      "description": "A list with executed stage results",
      "type": "array",
      "items": {
        "$ref": "flowStage.json"
      }
    }
  }
}

=== folio-org/mgr-tenant-entitlements/src/main/resources/swagger.api/samples/response/applicationFlowIncludeStages.json
{
  "id": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
  "applicationId": "application-foo-1.0.0",
  "tenantId": "6ad28dae-7c02-4f89-9320-153c55bf1914",
  "flowId": "06542b5a-7c37-46c9-a350-8d980f88e4ba",
  "type": "entitle",
  "status": "finished",
  "startedAt": "2023-01-28T11:27:36.951+00:00",
  "finishedAt": "2023-01-28T11:29:02.492+00:00",
  "stages": [
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "EntitlementFlowInitializer",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:36.947+00:00",
      "finishedAt": "2023-01-28T11:27:36.955+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "TenantLoader",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:36.958+00:00",
      "finishedAt": "2023-01-28T11:27:36.985+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "ApplicationDescriptorLoader",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:36.988+00:00",
      "finishedAt": "2023-01-28T11:27:37.101+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "ApplicationDependencyValidator",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:37.104+00:00",
      "finishedAt": "2023-01-28T11:27:37.109+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "ApplicationDiscoveryLoader",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:37.112+00:00",
      "finishedAt": "2023-01-28T11:27:37.206+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "KongGatewayRouteRegistrar",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:37.210+00:00",
      "finishedAt": "2023-01-28T11:27:42.735+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "OkapiModuleInstaller",
      "status": "finished",
      "startedAt": "2023-01-28T11:27:37.210+00:00",
      "finishedAt": "2023-01-28T11:28:59.146+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "EntitlementEventPublisher",
      "status": "finished",
      "startedAt": "2023-01-28T11:28:59.152+00:00",
      "finishedAt": "2023-01-28T11:29:02.477+00:00"
    },
    {
      "applicationFlowId": "2c4ffa97-7d3c-4a7c-9ab0-96d1ad99b2f9",
      "name": "EntitlementFlowFinalizer",
      "status": "finished",
      "startedAt": "2023-01-28T11:29:02.482+00:00",
      "finishedAt": "2023-01-28T11:29:02.496+00:00"
    }
  ]
}
